/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Atividade2;

/**
 *
 * @author 722414878
 */
public class PesoPlanetas extends javax.swing.JFrame {

    /**
     * Creates new form PesoPlanetas
     */
    public PesoPlanetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPesoTerra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bMercurio = new javax.swing.JRadioButton();
        bVenus = new javax.swing.JRadioButton();
        bMarte = new javax.swing.JRadioButton();
        bSaturno = new javax.swing.JRadioButton();
        bUrano = new javax.swing.JRadioButton();
        bJupter = new javax.swing.JRadioButton();
        jResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calcular Peso");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Peso na terra(kg):");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Selecione o Planeta:");

        buttonGroup1.add(bMercurio);
        bMercurio.setText("Mercúrio");
        bMercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMercurioActionPerformed(evt);
            }
        });

        buttonGroup1.add(bVenus);
        bVenus.setText("Vênus");
        bVenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVenusActionPerformed(evt);
            }
        });

        buttonGroup1.add(bMarte);
        bMarte.setText("Marte");
        bMarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMarteActionPerformed(evt);
            }
        });

        buttonGroup1.add(bSaturno);
        bSaturno.setText("Saturno");
        bSaturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaturnoActionPerformed(evt);
            }
        });

        buttonGroup1.add(bUrano);
        bUrano.setText("Urano");
        bUrano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUranoActionPerformed(evt);
            }
        });

        buttonGroup1.add(bJupter);
        bJupter.setText("Júpter");
        bJupter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJupterActionPerformed(evt);
            }
        });

        jResultado.setEditable(false);
        jResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPesoTerra, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bMercurio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bMarte))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bVenus)
                                .addGap(18, 18, 18)
                                .addComponent(bJupter)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSaturno)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bUrano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(jResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPesoTerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bMercurio)
                    .addComponent(bMarte)
                    .addComponent(bSaturno))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bVenus)
                            .addComponent(bUrano)
                            .addComponent(bJupter))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMercurioActionPerformed
        float pesoTerra = Float.parseFloat(jPesoTerra.getText());
        float p = (float) ((pesoTerra / 10) * 3.7);
        jResultado.setText(String.valueOf(p));

    }//GEN-LAST:event_bMercurioActionPerformed

    private void bVenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVenusActionPerformed
        float pesoTerra = Float.parseFloat(jPesoTerra.getText());
        float p = (float) ((pesoTerra / 10) * 8.8);
        jResultado.setText(String.valueOf(p));
    }//GEN-LAST:event_bVenusActionPerformed

    private void bMarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMarteActionPerformed
        float pesoTerra = Float.parseFloat(jPesoTerra.getText());
        float p = (float) ((pesoTerra / 10) * 3.8);
        jResultado.setText(String.valueOf(p));
    }//GEN-LAST:event_bMarteActionPerformed

    private void bSaturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaturnoActionPerformed
        float pesoTerra = Float.parseFloat(jPesoTerra.getText());
        float p = (float) ((pesoTerra / 10) * 11.5);
        jResultado.setText(String.valueOf(p));
    }//GEN-LAST:event_bSaturnoActionPerformed

    private void bUranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUranoActionPerformed
        float pesoTerra = Float.parseFloat(jPesoTerra.getText());
        float p = (float) ((pesoTerra / 10) * 11.7);
        jResultado.setText(String.valueOf(p));
    }//GEN-LAST:event_bUranoActionPerformed

    private void bJupterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJupterActionPerformed
        float pesoTerra = Float.parseFloat(jPesoTerra.getText());
        float p = (float) ((pesoTerra / 10) * 26.4);
        jResultado.setText(String.valueOf(p));
    }//GEN-LAST:event_bJupterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesoPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesoPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesoPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesoPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesoPlanetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bJupter;
    private javax.swing.JRadioButton bMarte;
    private javax.swing.JRadioButton bMercurio;
    private javax.swing.JRadioButton bSaturno;
    private javax.swing.JRadioButton bUrano;
    private javax.swing.JRadioButton bVenus;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jPesoTerra;
    private javax.swing.JTextField jResultado;
    // End of variables declaration//GEN-END:variables
}
