package interfaces;

import java.sql.SQLException;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PesquisarT extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pesquisar
     */
    private JDesktopPane principal0;

    public PesquisarT(JDesktopPane jdp) {
        initComponents();
        principal0 = jdp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomePesquisar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBPESQUISAR = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProduto = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nome");

        jBPESQUISAR.setText("Pesquisar");
        jBPESQUISAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPESQUISARActionPerformed(evt);
            }
        });

        jButton1.setText("Novo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jtProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Marca", "Custo", "Venda", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(nomePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jBPESQUISAR)
                .addGap(33, 33, 33)
                .addComponent(jBExcluir)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(jBEditar))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nomePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBPESQUISAR)
                    .addComponent(jBExcluir)
                    .addComponent(jButton1)
                    .addComponent(jBEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CadastrarEditar cadastrarEditar = new CadastrarEditar(principal0);
        principal0.add(cadastrarEditar);
        cadastrarEditar.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBPESQUISARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPESQUISARActionPerformed
        String nome = nomePesquisar.getText();
        DefaultTableModel model = (DefaultTableModel) jtProduto.getModel();
        try {
            a3crud.Conexao.pesquisarBd(nome, model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar Produtos: " + e.getMessage());
        }


    }//GEN-LAST:event_jBPESQUISARActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed

        if (jtProduto.getSelectedRow() != -1) {
            int linha = this.jtProduto.getSelectedRow();
            int idD = Integer.parseInt(jtProduto.getValueAt(linha, 0).toString());
            a3crud.Conexao.deletarBd(idD);
        } else {
            JOptionPane.showMessageDialog(null, "Produto(s) n?o selecionado(s)");
        }


    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        if (jtProduto.getSelectedRow() != -1) {
            int linha = jtProduto.getSelectedRow();
            int idD = Integer.parseInt(jtProduto.getValueAt(linha, 0).toString());
            String nome = jtProduto.getValueAt(linha, 1).toString();
            String marca = jtProduto.getValueAt(linha, 2).toString();
            double custo = Double.parseDouble(jtProduto.getValueAt(linha, 3).toString());
            double venda = Double.parseDouble(jtProduto.getValueAt(linha, 4).toString());
            int quantidade = Integer.parseInt(jtProduto.getValueAt(linha, 5).toString());
            EditarT editarproduto = new EditarT(principal0, idD, nome, marca, custo, venda, quantidade);
            principal0.add(editarproduto);
            editarproduto.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione algum produto!");
        }


    }//GEN-LAST:event_jBEditarActionPerformed

    /**
     * @param args the command line arguments public static void main(String
     * args[]) { /* Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
       * java.awt.EventQueue.invokeLater(new Runnable() {
        *    public void run() {
         *       //new Pesquisar().setVisible(true);
          *  }
       * });
   * }
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBPESQUISAR;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtProduto;
    private javax.swing.JTextField nomePesquisar;
    // End of variables declaration//GEN-END:variables
}
